controllers/user-controller.js
package-lock.json
package.json
public/stylesheets/style.css
routes/index.js
views/layouts/main.hbs
views/login.hbs

新增了user-controller資料夾和login.hbs
CSS增加了字體和字體權重的設定
package.json 的scripts部分，因為我用windows，所以指令不一樣。合併時可能會有衝突
===========================================
後續更改
修改login.hbs、修改main.hbs、修改route/index.js和下載cross-env

feat: add login page

---

public/stylesheets/style.css
views/layouts/main.hbs
views/partials/following-avatar.hbs
views/partials/rightbar.hbs
views/partials/user-avatar.hbs
views/tweets.hbs

主畫面的user modal和reply modal樣式完成

Merry tweets page modal

---

views/users.hbs

feat: modify users.hbs

---

controllers/user-controller.js
routes/index.js
views/login.hbs
views/register.hbs

新增註冊頁
更改login.hbs
========================
後續更動
使用 Camel Case

feat: add regiser_page and modify login_page

---

controllers/user-controller.js
routes/index.js
views/setting.hbs

feat: add setting page

---

controllers/tweet-controller.js
routes/index.js
views/tweets.hbs

tweets page can display seeder name, account, description

View all tweets page

---

routes/index.js
views/login.hbs

feat: add signin function

---

migrations/20230321144761-add-TweetId-to-likes.js
routes/index.js

rename Tweet_id to tweet_id in Like table

Merry replies page

---

app.js
controllers/user-controller.js
middleware/auth.js
routes/index.js
views/users/profile.hbs

增加追蹤與取消追蹤功能，修改路徑 '/' 導向 '/tweets'。

add follow function and modify route '/'

---

controllers/user-controller.js
views/users/profile.hbs
views/users/replies.hbs

modify profile.hbs, replies.hbs and user-controller.js

modify profile.hbs, replies.hbs and user-controller.js

---

controllers/user-controller.js
views/users/replies.hbs

modify replies.hbs; bug fixing

modify replies.hbs; bug fixing

---

controllers/user-controller.js
views/users/likes.hbs
views/users/profile.hbs
views/users/replies.hbs

modify likes.hbs, profile.hbs, replies.hbs and user-controller

modify likes.hbs, profile.hbs, replies.hbs and user-controller

---

controllers/user-controller.js
views/partials/follower-tabs.hbs
views/users/followers.hbs
views/users/followings.hbs

feat: add userFollowPage

---

README.md

Merry tweets page

---

controllers/user-controller.js
views/users/followers.hbs
views/users/followings.hbs

修改瀏覽他人追隨者和正在追隨跑出 "不能瀏覽他人追隨名單" 的錯誤
這本來是我自己加的，但demo時發現這樣好像有點奇怪。所以決定拿掉

feat: modify userFollowPage

---

app.js
config/passport.js
controllers/admin-controller.js
controllers/tweet-controller.js
package-lock.json
views/partials/rightbar.hbs

修改flash message和刪除 JWT strategy

feat: modify flash message and delete JWT

---

README.md

feat: update suite

---

public/stylesheets/style.css
public/stylesheets/viewStyles.css
views/register.hbs

feat: modify leftbar and rightbar

---

public/stylesheets/style.css
views/replies.hbs
views/setting.hbs
views/tweets.hbs
views/users/followers.hbs
views/users/followings.hbs
views/users/likes.hbs
views/users/profile.hbs
views/users/replies.hbs

feat: modify row

---

public/stylesheets/style.css
views/replies.hbs
views/tweets.hbs
views/users/followers.hbs
views/users/followings.hbs
views/users/likes.hbs
views/users/profile.hbs
views/users/replies.hbs

feat: modify tweet page

---

views/partials/rightbar.hbs

feat: fix rightbar ui

---

views/replies.hbs
views/tweets.hbs

fix font size, font color, font weight

feat: fix font

---

public/stylesheets/style.css
views/layouts/main.hbs
views/partials/rightbar.hbs
views/replies.hbs
views/setting.hbs
views/tweets.hbs
views/users/followers.hbs
views/users/followings.hbs
views/users/likes.hbs
views/users/profile.hbs
views/users/replies.hbs

CSS update
